#compdef casc-tool
# generated by `casc-tool --print-completion=zsh` -- do not hand-edit; regenerate with that command whenever a command's option table changes.

_casc_tool() {
    local -a subcommands
    subcommands=(
        'diff:compare two listfile snapshots'
        'extract:extract a single file to disk'
        'extract-batch:bulk-extract matching files to a directory'
        'info:show metadata for one file'
        'list:list files in a CASC storage'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case ${words[2]} in
        diff)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--format[Output format. Default: text]:value:(text csv json)' \
                '*:arg:_files'
            ;;
        extract)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--storage[CASC storage root (a directory containing .build.info). Default: . (current directory)]:value:_files -/' \
                '--listfile[FileDataID<->path mapping, e.g. wow-listfile'\''s community-listfile.csv. Default: listfile.csv (current directory)]:value:_files' \
                '--locale[One of: all (default), none, enus, engb, dede, frfr, eses, esmx, ruru, ptbr, ptpt, itit, kokr, zhcn, zhtw, encn, entw]:value:_files' \
                '--keys[Optional TACT decryption keys file (same format as wow.tools'\''s tactkeys API: '\''KeyName KeyValue'\'' hex pairs, one per line)]:value:_files' \
                '--product[Optional product codename, for installs with more than one flavor (e.g. '\''wow'\'', '\''wowt'\'' for PTR)]:value:_files' \
                '*:arg:_files'
            ;;
        extract-batch)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--storage[CASC storage root (a directory containing .build.info). Default: . (current directory)]:value:_files -/' \
                '--listfile[FileDataID<->path mapping, e.g. wow-listfile'\''s community-listfile.csv. Default: listfile.csv (current directory)]:value:_files' \
                '--locale[One of: all (default), none, enus, engb, dede, frfr, eses, esmx, ruru, ptbr, ptpt, itit, kokr, zhcn, zhtw, encn, entw]:value:_files' \
                '--keys[Optional TACT decryption keys file (same format as wow.tools'\''s tactkeys API: '\''KeyName KeyValue'\'' hex pairs, one per line)]:value:_files' \
                '--product[Optional product codename, for installs with more than one flavor (e.g. '\''wow'\'', '\''wowt'\'' for PTR)]:value:_files' \
                '--from-list[Extract exactly these FileDataIDs (one decimal ID per line) instead of matching a mask -- one storage open, no glob walk. Replaces <mask>; still takes <out-dir>]:value:_files' \
                '--unresolved-only[Only extract entries with no name in --listfile (written as <out-dir>/_unresolved/FILE########.dat). Not valid with --from-list -- an explicit ID list is neither resolved nor unresolved, it'\''s just itself]' \
                '--dry-run[Report what would be extracted (count, total bytes) without writing anything]' \
                '*:arg:_files -/'
            ;;
        info)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--storage[CASC storage root (a directory containing .build.info). Default: . (current directory)]:value:_files -/' \
                '--listfile[FileDataID<->path mapping, e.g. wow-listfile'\''s community-listfile.csv. Default: listfile.csv (current directory)]:value:_files' \
                '--locale[One of: all (default), none, enus, engb, dede, frfr, eses, esmx, ruru, ptbr, ptpt, itit, kokr, zhcn, zhtw, encn, entw]:value:_files' \
                '--keys[Optional TACT decryption keys file (same format as wow.tools'\''s tactkeys API: '\''KeyName KeyValue'\'' hex pairs, one per line)]:value:_files' \
                '--product[Optional product codename, for installs with more than one flavor (e.g. '\''wow'\'', '\''wowt'\'' for PTR)]:value:_files' \
                '--format[Output format. Default: text]:value:(text json)' \
                '*:arg:_files'
            ;;
        list)
            _arguments \
                '(-h --help)'{-h,--help}'[print help and exit]' \
                '--storage[CASC storage root (a directory containing .build.info). Default: . (current directory)]:value:_files -/' \
                '--listfile[FileDataID<->path mapping, e.g. wow-listfile'\''s community-listfile.csv. Default: listfile.csv (current directory)]:value:_files' \
                '--locale[One of: all (default), none, enus, engb, dede, frfr, eses, esmx, ruru, ptbr, ptpt, itit, kokr, zhcn, zhtw, encn, entw]:value:_files' \
                '--keys[Optional TACT decryption keys file (same format as wow.tools'\''s tactkeys API: '\''KeyName KeyValue'\'' hex pairs, one per line)]:value:_files' \
                '--product[Optional product codename, for installs with more than one flavor (e.g. '\''wow'\'', '\''wowt'\'' for PTR)]:value:_files' \
                '--unresolved-only[Only show entries with no name in --listfile (FileDataID-only) -- the actual worklist for growing the community listfile after a patch]' \
                '--format[Output format. Default: text]:value:(text csv json)' \
                '--limit[Max rows to print, 0 = unlimited. Default: 100 (applies to every format)]:value:_files' \
                '*:arg:_files'
            ;;
    esac
}

_casc_tool "$@"
