# generated by `casc-tool --print-completion=bash` -- do not hand-edit; regenerate with that command whenever a command's option table changes.
_casc_tool_completions() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local subcommands="diff extract extract-batch info list"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))
        return
    fi

    case "${COMP_WORDS[1]}" in
        diff)
            case "$prev" in
                --format)
                    COMPREPLY=($(compgen -W "text csv json" -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --format" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        extract)
            case "$prev" in
                --storage)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --listfile)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --locale)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --keys)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --product)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --storage --listfile --locale --keys --product --strict-encrypted" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        extract-batch)
            case "$prev" in
                --storage)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --listfile)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --locale)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --keys)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --product)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --from-list)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --storage --listfile --locale --keys --product --from-list --unresolved-only --dry-run --strict-encrypted" -- "$cur"))
                return
            fi
            compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
            ;;
        info)
            case "$prev" in
                --storage)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --listfile)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --locale)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --keys)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --product)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --format)
                    COMPREPLY=($(compgen -W "text json" -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --storage --listfile --locale --keys --product --format" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
        list)
            case "$prev" in
                --storage)
                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- "$cur"))
                    return
                    ;;
                --listfile)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --locale)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --keys)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --product)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
                --format)
                    COMPREPLY=($(compgen -W "text csv json" -- "$cur"))
                    return
                    ;;
                --limit)
                    COMPREPLY=($(compgen -f -- "$cur"))
                    return
                    ;;
            esac
            if [[ "$cur" == -* ]]; then
                COMPREPLY=($(compgen -W "--help -h --storage --listfile --locale --keys --product --unresolved-only --format --limit" -- "$cur"))
                return
            fi
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
    esac
}
complete -F _casc_tool_completions casc-tool
