#include "completion.hpp"

#include <set>
#include <sstream>
#include <stdexcept>

#include "registry.hpp"

// `completions/casc-tool.bash`/`.zsh` (checked in) are captured output of
// `casc-tool --print-completion=<bash|zsh>`, not hand-written -- ported
// from husk's own `--print-completion` design (see husk's DESIGN.md,
// "Shell completion generation"). The generators below walk
// registry::commandTable(), which holds each command's *real*
// cli::OptionSpec list (the exact same one that command's own --help and
// argument parser already use), instead of a second, hand-maintained flag
// list -- the whole point being that a completion script can never drift
// from what the tool actually accepts, because there both read from one
// source. (No CLI11-style introspection API needed here the way husk's
// port required one, since casc-tool's own OptionSpec vectors already are
// that live metadata, deliberately -- see cli.hpp's own top comment on
// why this tool rolls its own minimal parser instead of a library.)
//
// What's *not* derived from OptionSpec, and is instead a small hand-kept
// table below (same tier as husk's own per-flag --textures-out/--skin-dir
// directory-vs-file hints): which flags/positionals expect a directory
// rather than a plain file. OptionSpec has no such field (it's a flag
// name/value-hint/help triple, nothing richer), so this is genuinely
// outside what generation-from-real-metadata can give for free.
namespace completion {

namespace {

// --storage is the one common flag that's a directory (contains
// .build.info), not a file -- everything else that takes a path
// (--listfile, --keys, --from-list, diff's positionals, ...) is a plain
// file. Kept as its own tiny set rather than inferring from valueHint text,
// since "<path>" is used for both storage and listfile today.
bool isDirFlag(const std::string& flagName) { return flagName == "--storage"; }

// extract-batch is the one command whose last positional (out-dir) is a
// directory the user is choosing to create/reuse, not a file to open --
// worth completing as such. Every other command's bare positionals are
// files (a model/listfile path) or a FileDataID, both file-completion-ish.
bool lastPositionalIsDir(const std::string& commandName) { return commandName == "extract-batch"; }

// Pulls an explicit value enum out of a valueHint like "<text|csv|json>",
// or returns an empty vector if the hint isn't pipe-delimited (e.g. "<n>",
// "<path>", "<codename>" -- free-form values with nothing to enumerate).
std::vector<std::string> enumValues(const std::string& valueHint) {
    if (valueHint.size() < 2 || valueHint.front() != '<' || valueHint.back() != '>') return {};
    std::string inner = valueHint.substr(1, valueHint.size() - 2);
    if (inner.find('|') == std::string::npos) return {};
    std::vector<std::string> out;
    std::stringstream ss(inner);
    std::string item;
    while (std::getline(ss, item, '|')) out.push_back(item);
    return out;
}

// Escapes a string for use inside a single-quoted zsh literal (the shape
// _arguments spec strings need): each embedded `'` becomes `'\''` (close
// the quote, emit an escaped quote, reopen). Several real help strings in
// this tool contain apostrophes ("wow.tools's", "it's just itself"), so
// this isn't a defensive-only precaution -- skipping it produces a broken
// generated script today, not just hypothetically.
std::string zshEscape(const std::string& s) {
    std::string out;
    for (char c : s) {
        if (c == '\'') out += "'\\''";
        else out += c;
    }
    return out;
}

std::string join(const std::vector<std::string>& items, const std::string& sep) {
    std::string out;
    for (size_t i = 0; i < items.size(); i++) {
        if (i > 0) out += sep;
        out += items[i];
    }
    return out;
}

std::string generateBash() {
    std::ostringstream out;
    out << "# generated by `casc-tool --print-completion=bash` -- do not hand-edit; "
           "regenerate with that command whenever a command's option table changes.\n"
           "_casc_tool_completions() {\n"
           "    local cur prev\n"
           "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
           "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
           "\n";

    std::vector<std::string> names;
    for (const auto& [name, cmd] : registry::commandTable()) names.push_back(name);
    out << "    local subcommands=\"" << join(names, " ") << "\"\n"
        << "\n"
        << "    if [[ $COMP_CWORD -eq 1 ]]; then\n"
        << "        COMPREPLY=($(compgen -W \"$subcommands\" -- \"$cur\"))\n"
        << "        return\n"
        << "    fi\n"
        << "\n"
        << "    case \"${COMP_WORDS[1]}\" in\n";

    for (const auto& [name, cmd] : registry::commandTable()) {
        out << "        " << name << ")\n"
            << "            case \"$prev\" in\n";
        std::vector<std::string> flagNames = {"--help", "-h"};
        for (const auto& spec : cmd.specs()) {
            flagNames.push_back(spec.name);
            if (!spec.takesValue) continue;
            out << "                " << spec.name << ")\n";
            auto values = enumValues(spec.valueHint);
            if (!values.empty()) {
                out << "                    COMPREPLY=($(compgen -W \"" << join(values, " ") << "\" -- \"$cur\"))\n";
            } else if (isDirFlag(spec.name)) {
                out << "                    compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- \"$cur\"))\n";
            } else {
                out << "                    COMPREPLY=($(compgen -f -- \"$cur\"))\n";
            }
            out << "                    return\n"
                << "                    ;;\n";
        }
        out << "            esac\n"
            << "            if [[ \"$cur\" == -* ]]; then\n"
            << "                COMPREPLY=($(compgen -W \"" << join(flagNames, " ") << "\" -- \"$cur\"))\n"
            << "                return\n"
            << "            fi\n";
        if (lastPositionalIsDir(name)) {
            out << "            compopt -o filenames 2>/dev/null; COMPREPLY=($(compgen -d -- \"$cur\"))\n";
        } else {
            out << "            COMPREPLY=($(compgen -f -- \"$cur\"))\n";
        }
        out << "            ;;\n";
    }

    out << "    esac\n"
        << "}\n"
        << "complete -F _casc_tool_completions casc-tool\n";
    return out.str();
}

std::string generateZsh() {
    std::ostringstream out;
    out << "#compdef casc-tool\n"
        << "# generated by `casc-tool --print-completion=zsh` -- do not hand-edit; "
           "regenerate with that command whenever a command's option table changes.\n"
        << "\n"
        << "_casc_tool() {\n"
        << "    local -a subcommands\n"
        << "    subcommands=(\n";
    for (const auto& [name, cmd] : registry::commandTable()) {
        out << "        '" << name << ":" << zshEscape(cmd.oneLine) << "'\n";
    }
    out << "    )\n"
        << "\n"
        << "    if (( CURRENT == 2 )); then\n"
        << "        _describe 'command' subcommands\n"
        << "        return\n"
        << "    fi\n"
        << "\n"
        << "    case ${words[2]} in\n";

    for (const auto& [name, cmd] : registry::commandTable()) {
        out << "        " << name << ")\n"
            << "            _arguments \\\n"
            << "                '(-h --help)'{-h,--help}'[print help and exit]' \\\n";
        for (const auto& spec : cmd.specs()) {
            std::string action;
            if (!spec.takesValue) {
                action = "";
            } else {
                auto values = enumValues(spec.valueHint);
                if (!values.empty()) {
                    action = ":value:(" + join(values, " ") + ")";
                } else if (isDirFlag(spec.name)) {
                    action = ":value:_files -/";
                } else {
                    action = ":value:_files";
                }
            }
            out << "                '" << spec.name << "[" << zshEscape(spec.help) << "]" << action << "' \\\n";
        }
        out << "                '*:arg:" << (lastPositionalIsDir(name) ? "_files -/" : "_files") << "'\n"
            << "            ;;\n";
    }

    out << "    esac\n"
        << "}\n"
        << "\n"
        << "_casc_tool \"$@\"\n";
    return out.str();
}

}  // namespace

std::string generate(const std::string& shell) {
    if (shell == "bash") return generateBash();
    if (shell == "zsh") return generateZsh();
    throw std::runtime_error("--print-completion: unsupported shell '" + shell + "' (want 'bash' or 'zsh')");
}

}  // namespace completion
